name: DuckspecProjectSettings
description: Configuration for an @DuckspecProject.
extends: @Settings
properties:
  - name: terms_folder
    required: true
    description: relative path to the folder where @Term files for this @DuckspecProject are stored; relative to the @DuckspecProject term file's location
  - name: readme
    description: path to the root description file of the @Project (e.g. README.md); relative to the @DuckspecProject term file's location
  - name: agents
    description: path to the AGENTS.md file with model loading instructions; relative to the @DuckspecProject term file's location
