name: Project
description: Base term for project definitions.
contains:
  - name: goals
    description: list of @Goal the @Project pursues
  - name: guidelines
    description: list of @Guideline the @Project defines
  - name: software
    description: list of @Software the @Project contains
  - name: uses
    description: list of @Project this @Project uses or depends on
